### PR TITLE
Update ssh-askpass

### PR DESCRIPTION
**Pull request by mboisson**
Resolves https://github.com/theseal/ssh-askpass/issues/26 and https://github.com/theseal/ssh-askpass/issues/40
as suggested by the OP, using default button 1 fixes that issue

### CODE REVIEW

**Comment by simmel** [comment]
LGTM!

I wonder how it works for people with a right to left locale?

**Comment by mboisson** [comment]
Didn't you test that in this comment ? :) https://github.com/theseal/ssh-askpass/issues/26#issuecomment-1479468015

**Comment by simmel** [comment]
Haha, the best questions answer them selves? XDgj!On 17 Aug 2023, at 20:44, Maxime Boissonneault ***@***.***> wrote:﻿
Didn't you test that in this comment ? :) #26 (comment)

**Comment by theseal** [comment]
LGTM, thanks!

**Pull request merged**
