### PR TITLE
brew install in oneliner

### PR DESCRIPTION
**Pull request by netj**
no need to tap first then install

### CODE REVIEW

**Comment by simmel** [comment]
Gotta tap that! Got any feeling how new this feature is @netj ?

**Comment by theseal** [comment]
I think this feature has been around since forever.

**Comment by netj** [comment]
Yes I believe so. (At least since 2012, looking at my own [netj/homebrew-tap.git](https://github.com/netj/homebrew-tap/commit/7e1d64a4819894dfcbcb2e6682f5097362b2a2c7).)
If the repo name follows the convention `fork/homebrew-foo.git` then the command could be simply `brew install fork/foo/formula`, but it still works even if it doesn't, which is nice.

**Comment by simmel** [comment]
Thank you @netj!

**Pull request merged**
