### PR TITLE
Non SIP method of install

### PR DESCRIPTION
**Pull request by bharrisau**

### CODE REVIEW

**Comment by theseal** [comment]
Great idea! 😄
I think it's a better idea if we put the plist in the users LaunchAgents directory (~/Library/LaunchAgents/) instead if the system global LaunchDaemons directory.
By doing so we can skip `sudo`!

I'm no expert on `launchd` but I think you need to add:
```
 <key>RunAtLoad</key>
 <true/>
```
to make it start at load and login.

**Comment by simmel** [comment]
If I understood the [man page](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man5/launchd.plist.5.html) correctly it should `launch on demand sockets` i.e. when `ssh(1)` or any other application tries to use the socket it will launch.

But yes, let's put it in homebrew-ssh-askpass instead. :+1:

**Comment by theseal** [comment]
The "socket thing"
```
  <key>Sockets</key>
  <dict>
    <key>Listeners</key>
    <dict>
      <key>SecureSocketWithKey</key>
      <string>SSH_AUTH_SOCK</string>
    </dict>
  </dict>
```
didn't work for me earlier today, but now then trying it work just fine. So never mind my commend about
```
<key>RunAtLoad</key>
 <true/>
```
Could be worth commenting in the instruction that you MAY need to login and out depending if you have started the ssh-agent already and it might be easier if we had the plist as a seperate file that user just copying to  `~/Library/LaunchAgents/`

I can see a point of having the plist here as well as in [homebrew-ssh-askpass](https://github.com/theseal/homebrew-ssh-askpass) since not everyone is using homebrew. Would you mind making a PR in that repo too, @bharrisau?

**Comment by bharrisau** [comment]
Then I will update the snippet and add a similar file to the homebrew repo. I expect to get to it in the next 24 hours.

**Pull request closed without merging**
