### PR TITLE
Now handles user input prompts (e.g. username/password) as well as binary prompts.

### PR DESCRIPTION
**Pull request by alexreg**
Resolves issue #14.
Rewrote script in JXA (JavaScript for automation).

### CODE REVIEW

**Comment by theseal** [comment]
Thanks for the PR.
I will take a closer look on it in a few days.  👍

**Comment by theseal** [comment]
Thanks for your contribution!

We are right now not ready rewrite this project in an other language.
However we were inspired by your code and made this [commit](https://github.com/theseal/ssh-askpass/commit/65592db72d0a114e5542799a26e30a9f6a42eff7) with your logic but written in AppleScript. It's also closes #14 but in a more native way for this project.
Is it OK with you if we commit that code in your name, give you credit in the commit or just commit the code without any reference?

**Comment by alexreg** [comment]
@theseal That's fine for now. It loses some of the nuances in my code, but it's definitely an enhancement. (I decided to rewrite in JavaScript mainly because I just hate AppleScript as a language.) Feel free to commit the code in my name, or whatever. :)

Also, I'll probably leave my fork around for now, if that's alright. Not that there will be much activity on it...

**Comment by simmel** [comment]
Cool, done.

AppleScript has it's merits (mostly the OS X integration) but yes; it's not my favorite language = )

Thank you for your contribution Alexander!

**Comment by alexreg** [comment]
JXA has OS X integration too. :) It misses a few of the features of AppleScript, but you can always fall back to the Cocoa APIs, so you can do everything you can in AppleScript, and you make up for it with a more powerful and superior language.

Anyway, glad to help!

**Pull request closed without merging**
